env:
  global:
    - CC_TEST_REPORTER_ID=3a0a0d4a4f50f803d61a12a6527daaebb37345ebe45ac0ad8ff1a496216892d4
language: ruby
rvm:
- 2.3.5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter format-coverage --output "coverage/codeclimate.$N.json" -t simplecov
  - ./cc-test-reporter upload-coverage -r default
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t simplecov
deploy:
  provider: heroku
  api_key:
    secure: NOlDbtQiKeMZFRKc1tpCKu1pKMc2//JCgOsS6ip7oRRfrxETgaziCNO86xrneHr3ETjQCi3e8fYJx/cXnOesc7M/GIKBIvI+bSlAut2FsCy9M2QStn0XduRs9vM2r5Ri3o+nep4tQXoC7ZChIczS3noF6HabyM6ZPUHV2t/XyGVg1xaoyezQpFVRXRolK/bb3nZAyWo/AVz+ep0TmPmZsGGiOuCBV7mNP8323Kxren8dnZfoN1RiClxMXAGbShnSaIO3Urzmyw7Dr/2sIIs7QwnDCA/RhgD2Yr5Xynx2MSs1goHUFwDZnb2pTBjJbSDESIR/lEB8KJkukbjaSUcN2F1PY+xgTyM0jA7fDsG2HLHgat5tVSVpqaz43J4LJq2H+wS21pB9hOa5T1cpCAzClI7eDXju1eY+C6ULjlzKKRL5VgkCbAw+0O3hxf11HCW18cCHtaBqkDg6LgahCizKJnhNfl2jbenJo9HKJF2OYcFfI6Zv3tM2ReE5Z05wBEumXw5E7kbizQdEJVVVXPDo9iJnz0SgHF3qeSj15HamB0s0uuYTXKiezvjQYAcMmS9oTvFAUkjnMDgdl2AaIQBlNamRktrqg58emq047+l8lL4VUiRAt8FOrJAxg3aNLkpaFuR0exaY3LAQJp/QY/e8n1d7q8kBn/mhAFN/A1i1Af4=
  run: "rake db:migrate"
  app: web-app-ruby-utbm
  
