language: ruby
rvm:
- 2.3.5
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: <%= ENV['API_KEY'] %>
  app: web-app-ruby-utbm